--Create few records in this table
INSERT INTO USER VALUES(1,'Tom');
INSERT INTO USER VALUES(2,'Lucy');
INSERT INTO USER VALUES(3,'Frank');
INSERT INTO USER VALUES(4,'Jane');
INSERT INTO USER VALUES(5,'Robert');